services:
  - type: web
    name: facelogin
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DEBUG
        value: "0"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
